import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import type { Metadata } from "next";
import { GameProvider } from "@/components/GameContext";
import "./globals.css";
import ConfettiClient from "@/components/ConfetiClient";
import Footer from "@/components/footer";
import Header from "@/components/header";

export const metadata: Metadata = {
	title: "Frontend Mentor | Typing Speed Test",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon-32x32.png",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	gsap.registerPlugin(useGSAP);
	gsap.defaults({
		force3D: true, // GPU acceleration
		lazy: false, // Immediate rendering
	});
	return (
		<html lang="en">
			<body className="font-bold min-h-screen relative group overflow-hidden bg-FemNeutral-900  text-FemNeutral-000 m-auto max-w-7xl">
				<GameProvider>
					<Header />
					{children}
					<ConfettiClient />
					<Footer />
				</GameProvider>
			</body>
		</html>
	);
}
