import Header from "@/components/header";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/footer";

export const metadata: Metadata = {
	title: "Frontend Mentor | Typing Speed Test",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon-32x32.png",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-bold min-h-screen relative group overflow-hidden bg-FemNeutral-900  text-FemNeutral-000 m-auto max-w-7xl">
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
